### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by Daniel15** [scottsweb/wp-instagram-widget#19]
Is there no official API you could use rather than scraping the site? Relying on JavaScript variables on the site is very fragile :)

**Comment by scottsweb** [comment]
There is an official api but the aim of this plugin (see readme.txt) was to provide a simple setup process.

The JS has changed twice since the plugin was launched, this is the first time it has affected the behaviour negatively. 

If it breaks again I will be switching to the api but there are plent of existing widgets that do this already.

**Comment by scottsweb** [comment]
There is also the secondary problem of either requiring people to setup their own Instagram app or distributing private app keys, publicly.
