### ISSUE TITLE
5xx Server Error

### ISSUE THREAD

**Issue by amslezak** [scottsweb/wp-instagram-widget#41]
Hello,

Thank you for creating this widget!

We're using Wordpress 4.4.1 and 1.9.4 of the Instagram widget, we are getting a "5xx Server Error" when images are trying to be accessed.

As an example, the URL that yields the error is:
http://scontent.cdninstagram.com/t51.2885-15/e15/s320x320

The site is cytexone.com, and the widget is located at the bottom in the footer.

![image](https://cloud.githubusercontent.com/assets/6944605/12653114/085e080a-c5bc-11e5-87be-fc56bb9eaede.png)

I checked Twitter and didn't see any CDN or API disruptions.  I'm just curious if you have any ideas on what the problem is?  It just started yesterday as far as I can tell and I haven't changed anything.

Thanks very much.

Andy

**Comment by daviedR** [comment]
+1 for this

Happens in my site too..

**Comment by scottsweb** [comment]
Please can you provide:

* PHP version
* WordPress version
* Plugin version
* Instagram Username
* A link to your site if possible
* A URL of the broken images
* Your selected image size within the widget settings
* If this happens to videos, images or both

I will be tracking the issue here: https://wordpress.org/support/topic/v-194-images-not-loaded?replies=2#post-7960819

**Comment by scottsweb** [comment]
Fixed in 1.9.5
